### ISSUE TITLE
Meaning of some of John Harrisons's types

### ISSUE THREAD

**Issue by laskowsp** [JacquesCarette/hol-light#1]
I am having a bit of trouble understanding what some of the types defined in John Harrison's paper actually do, namely:

Ind (I'm assuming this means an inductive type defined in terms of itself such as term's Comb or Abs, would a reliable way to check for these be to check for types that map to themselves such as :term->term?)
Equal type
Select type

What expressions would cause these terms to be generated when quoted?

**Comment by JacquesCarette** [comment]
I'll try to answer, but may not get to this until mid-afternoon.  @wmfarmer may be able to get to it sooner?

**Comment by wmfarmer** [comment]
Ind is a base type of individuals.  In the simplest version of Church's type theory, there are two base types o (omicron) and i (iota) which John Harrison calls Bool and Ind, respectively.  In the semantics of Church's type theory, Ind is specified only to be nonempty.

**Comment by laskowsp** [comment]
Thanks for the reply, just to make sure I understand correctly - Ind would therefore classify any atomic value that is not a boolean, such as a natural or real number?

**Comment by wmfarmer** [comment]
This is correct.  Every value that is not a function is either a boolean or an individual.  In most implementations of Church's type theory, any number of types of individuals are allowed.  So there could be a type for integers and another for real numbers.

**Comment by laskowsp** [comment]
Thank you for the clarification, Dr. Farmer.

What about Equal and Select? On closer inspection it looks like they would serve the same purpose as an operator constant in HOL - equal is easy enough to make sense of but what would the Select operator do? 

Furthermore, does this mean I would need to expand on the type with a term for each operator such as Add type, Multiply type, etc.?

**Comment by wmfarmer** [comment]
Your questions are getting us to the key question of how the type epsilon of constructions will be defined in HOL Light.  We are going to have to discuss this in person.  Could we meet tomorrow in my office at 9:30.

**Comment by laskowsp** [comment]
Yes, we can meet then.

**Comment by JacquesCarette** [comment]
Some comment as on issue #2.
