### ISSUE TITLE
Questions regarding beta conversion and evals

### ISSUE THREAD

**Issue by laskowsp** [JacquesCarette/hol-light#12]
I've noticed that beta conversion is slightly broken when working with evaluations in some specific cases, and I'd like to confirm that my assumptions about these are correct:

1. (\x. A) y where x and y are not the same, and A is not eval free but is also not an eval itself. For example, `(\x. 3 + (eval x to num) = x) 2` - should the y term be brought inwards to create something like `3 + (\x. eval x to num) 2 = 2`, or should something else happen?

2. (\x. A) y where x and y are different, A is eval free, but y is not eval free, such as `(\x. x) (eval x to num)`. I'm assuming here that nothing special needs to be done, the eval term can just be substituted in for x?

Thanks!

**Comment by wmfarmer** [comment]
You are correct in both cases.  The two things to remember are (1) substitution stops at evaluations and (2) it is not necessarily possible to tell if a variable is free in an evaluation.

**Comment by JacquesCarette** [comment]
Since it was Patrick who had asked this question, is there knowledge here that @sjjs7 should be aware of?

**Comment by wmfarmer** [comment]
The two points Patrick addresses are direct consequences of the substitution algorithm for CTTqe that she is familiar with.  I will make sure that she is aware of these two situations.
