### ISSUE TITLE
Regarding parameterized types

### ISSUE THREAD

**Issue by laskowsp** [JacquesCarette/hol-light#3]
I have discovered that my pseudoquotation implementation is incapable of quoting strings or lists - internally, a string is of type (char)list, while a list is generally of the type (A)list, where A can be any type. 

How could this be represented inside the `type` type? I know Tyvar can be used to represent "A", but how would this be combined with another type such as a list?

**Comment by JacquesCarette** [comment]
You will need 'type constructors'.  `list` is one of these.  So `list` is really a `type`-level function, which maps from `type` to `type`.  So you'll need to extend the grammar of `type` to allow type application.
