### ISSUE TITLE
Recrusion on list elements in HOL

### ISSUE THREAD

**Issue by laskowsp** [JacquesCarette/hol-light#4]
I am having issues with implementing isTypeValid - I need it to recursively check that the types given inside the list of types are valid as well. However, HOL refuses any attempts to do this because it cannot prove a wellfounded ordering.

I've looked at the tutorial (page 164) and the solution John Harrison uses in these circumstances is to define a recursive function to calculate the "size" of a problem and use that to prove that the problem size is constantly decreasing, but it refuses to do that too for the same reasons. 

Namely, this is the goal that I need to define an ordering to satisfy:
```
`?(<<). WF (<<) /\
        (!str a b. b << TyCons str [a; b]) /\
        (!str a b. a << TyCons str [a; b]) /\
        (!str a. a << TyCons str [a])`
```

**Comment by JacquesCarette** [comment]
Can't you define `size` to be the "obvious" thing (recurse, assign 1 to leaves, and 1+ size of leaves to `TyCons`) ?  That would certainly satisfy the above criterion.

**Comment by laskowsp** [comment]
Indeed I have tried that, it fails because of the same unproven property. Here is my attempt:
```
let so1 = prove_general_recursive_function_exists `?so1.
	(so1 (TyVar str) = 1) /\
	(so1 (TyCons str []) = 1) /\
	(so1 (TyCons str [a]) = 1 + (so1 a)) /\
	(so1 (TyCons str [a;b]) = 1 + (so1 a) + (so1 b))
`;;
```

**Comment by JacquesCarette** [comment]
I don't think it knows that lists are always length <= 2.  Best to map so1 onto the sublist, then `sum` the results (+1).

**Comment by laskowsp** [comment]
Alright, this requires defining my own SUM definition:
```
let SUM = new_recursive_definition list_RECURSION
  `(SUM [] = 0) /\
   (SUM (CONS h t) = h + SUM t)`;;
```
(A quick test confirms that it works as intended)

My so1 function is now:
```
let so1 = prove_general_recursive_function_exists `?so1.
	(so1 (TyVar str) = 1) /\
	(so1 (TyCons str l) = (SUM (MAP so1 l)) + 1)
`;;
```

It still fails to define, and now wants this proven:

```
?(<<). WF (<<) /\
           admissible (<<) (\f (str,l). T) (\(str,l). TyCons str l)
           (\so1 (str,l). SUM (MAP so1 l) + 1)
```

Edit: HOL defines "Admissible" to be:
```
 !p (<<) s t.
         admissible (<<) p s t <=>
         (!f g a.
              p f a /\ p g a /\ (!z. z << s a ==> f z = g z)
              ==> t f a = t g a)
```

**Comment by JacquesCarette** [comment]
Sorry, I've run out of ideas.  You'll have to dig deeper into how to tell HOL about well-founded orderings.

[Note: I am quite sure that `SUM` exists in the HOL library somewhere already!]

**Comment by laskowsp** [comment]
Alright, I'll continue to look into it. Thank you!

**Comment by laskowsp** [comment]
In regards to a potential solution to this problem - all types defined by default in HOL (and epsilon/type) take either 0, 1, or 2 "arguments" when they are constructed. Since the issue is caused by the list inside TyCons, the problem could be avoided altogether if type were defined as:

```
type =
TyVar string
| TyBase string
| TyMonoCons string type
| TyBiCons string type type
```

Would changing the system to use this format be a good idea?

**Comment by JacquesCarette** [comment]
Yes.  Because it builds your invariant (0, 1 or 2 arguments) into the definition 'structurally', which makes it easy to see for the underlying system.  So your proofs will become easier.
