### ISSUE TITLE
At what point should substitution no longer work on quotations?

### ISSUE THREAD

**Issue by laskowsp** [JacquesCarette/hol-light#6]
Dr. Farmer has told me that quotations have no free variables, and thus it should not be possible to substitute into one. My question is - at what stage does this happen? To quote something in my current implementation of HOL QE, you'd preface it with a `_Q_` , so the quotation of a boolean variable would go through three "stages":

`_Q_ (x:bool)`
Applying the theorem named `QUOTE` would result in:
`Q_ (x:bool) _Q`
And applying the theorem named `TERM_TO_CONSTRUCTION` would result in:
`QuoVar "x" (TyBase "bool")`

At which stage of this process should it no longer be possible to substitute into x, or should it not be allowed in all 3?

**Comment by JacquesCarette** [comment]
My feeling is that the _Q_ and Q_ version should be internal only (i.e. never visible if you are not a HOL developer).  Definitely the `QuoVar` stage has no variables.

Nevertheless, as to your main question: in none of the 3 stages should substitution be allowed.
